version: '2'

services:

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - ./data_influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana:/var/lib/grafana

volumes:
  data_influxdb:
  data_grafana:
  telegraf.conf:
